AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Rails:
  Enabled: true
Style/LambdaCall:
  Enabled: false
Metrics/ClassLength:
  Enabled: false